[package]
name = "expression"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
dirs = "6.0.0" # for cross-platform config dir
