[general]
backend = "swww"
enable_special = true
enable_sub_collection = true

[directories]
wallpaper = "/path/to/wallpapers"
# special = "/custom/path/to/special/"
# collections = "/custom/path/to/collections/"

# [special_entries]
# 5 = "wakeup"
# 7 = "breakfast"
# 9 = "workout"
# 12 = "lunch"
# 23 = "sleep"
